version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/app/artifacts
    volumes:
      - ./mlruns:/app/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /app/artifacts
      --host 0.0.0.0

  frontend:
    build:
      context: .
      dockerfile: CarsFrontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend